### ISSUE TITLE
Investigate header animation on mobile

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#964] opened 2020-10-01 17:43 UTC
We need to ensure that the animated header (typewriting effect) does not introduce unwanted shifts in the layout, due to some strings being longer than others.

**Comment by eddybrando** [comment] 2020-11-12 16:55
@techtolentino, I believe this may be a duplicate of https://github.com/Qiskit/qiskit.org/issues/920.

**Comment by delapuente** [comment] 2020-11-13 17:21
Indeed, this is covered by #920. Closing.

**Closed by delapuente** 2020-11-13 17:21 UTC
Labels: code-quality
