### ISSUE TITLE
create color scheme for circuits in the textbook

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2221] opened 2021-10-14 18:14 UTC
A color scheme for the circuits in the textbook can be created, similar to what is show here: https://github.com/Qiskit/qiskit-terra/tree/main/qiskit/visualization/styles

A new version could be created for the textbook, and set as default.

**Comment by lerongil** [comment] 2021-11-01 16:20
Duplicate of #2230

**Closed by lerongil** 2021-11-01 16:20 UTC
Labels: Design, education, needs grooming
