### ISSUE TITLE
Link to Qcamp 2020 still says March

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#459] opened 2020-03-17 10:33 UTC
### Steps to reproduce the problem
No one updated the link in the QCamp 2020 section: https://medium.com/qiskit/qiskit-camp-2020-coming-next-march-7b8c39e5d42c

It stills says March 10-13th:

> Qiskit Camp 2020, the 2nd annual flagship Qiskit Camp event, will take place from March 10th to 13th. This event will start in New York and include a traverse to Vermont.

**Comment by delapuente** [comment] 2020-03-17 11:54
Not a bug, not related to development nor operation of qiskit.org. Please, contact the content team.

**Comment by lerongil** [comment] 2020-03-17 20:17
@nonhermitian This should be updated now: https://medium.com/qiskit/qiskit-camp-2020-coming-next-march-7b8c39e5d42c. Thanks for the catch.

**Comment by delapuente** [comment] 2020-03-17 20:29
My apologies for my blunt answer before. I created a new "content issue" that I hope helps us tracking content issues such as typos, misspellings, out-of-date content and alike:
https://github.com/Qiskit/qiskit.org/issues/new?assignees=&labels=content&template=content_issue.md

**Comment by lerongil** [comment] 2020-03-23 05:49
Closing out this issue. Please reopen if not resolved.

**Closed by lerongil** 2020-03-23 05:49 UTC
Labels: content
