### ISSUE TITLE
Many textbook buttons do not link to next pages

### ISSUE THREAD

**Issue by nonhermitian** [Qiskit/qiskit.org#367] opened 2019-12-28 12:29 UTC
### Steps to reproduce the problem
1. Go to section x.1 (any `x` works here, i.e. 2.1)
2. Click on next at the bottom of the page.

### What is the current behavior?
The button links to the same page introduction.

### What is the expected behavior?
The navigator opens the next section.

**Comment by delapuente** [comment] 2019-12-30 08:20
We have a [separated repository](https://qiskit.org/qiskit/qiskit-textbook) for solving textbook issues. Indeed, this has been reported in qiskit/qiskit-textbook#128.

**Comment by delapuente** [comment] 2019-12-30 08:22
@aasfaw @lerongil we should talk about prioritizing textbook issues. Not closing until we decide on this.

**Comment by delapuente** [comment] 2020-01-20 10:18
The problem is that the titles are duplicated entries of the toc. When Jupyter Book computes the flat TOC it ends with a list with the form `0.1 -> 0.1 -> 0.2 -> 0.3 -> 1.1 -> 1.1 -> 1.2 -> 1.3` but it only generates one HTML page per Jupyter notebook, and so, linking `X.1 -> X.2` never happens.

**Comment by delapuente** [comment] 2020-01-20 10:20
Fixed by https://github.com/Qiskit/qiskit-textbook/pull/150

**Closed by delapuente** 2020-01-20 10:20 UTC
Labels: ON HOLD, size: L, type: bug, type: discussion
