### ISSUE TITLE
Replace mentions of deprecated Qiskit packages

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2466] opened 2022-01-28 04:01 UTC
Packages like [qiskit-aqua](https://github.com/Qiskit/qiskit-aqua) are now deprecated but we still mention and use them in our codebase.

We need to:

- [ ] Create a list of the deprecated messages
- [ ] Look for and remove or update mentions in the codebase

## Additional information

- every mention to `qiskit-ignis` and `qiskit-aqua` should be deleted.
- `qiskit-aer` and `qiskit-ibmq-provider` are not deprecated yet, but for any reference to `aer` outside the Quick Start we can check w/ DevRel

## Issues found
- [ ] https://github.com/Qiskit/qiskit.org/issues/2914
- [ ] https://github.com/Qiskit/qiskit.org/issues/2916

**Comment by techtolentino** [comment] 2023-01-09 21:15
@y4izus @eddybrando 

Any ideas on where we can find out what's deprecated?

I'm a little unclear on if this issue is actionable... seems like we still need to define what the updates should be?

**Comment by eddybrando** [comment] 2023-01-10 10:59
> Any ideas on where we can find out what's deprecated?

I think that asking the DevRel team might be a good idea.

> I'm a little unclear on if this issue is actionable... seems like we still need to define what the updates should be?

Maybe we could start with the first action item, which is about gathering the information about what changes are needed and listing them.

**Comment by techtolentino** [comment] 2023-01-10 13:36
Thanks @eddybrando 

This issue/PR seems related, and could potentially have overlap: https://github.com/Qiskit/qiskit.org/issues/2857

@1ucian0, would you say that this issue is a duplicate of ☝?

**Comment by y4izus** [comment] 2023-01-17 14:19
I've reviewed qiskit.org looking for deprecated packages and I've created two issues for working on it, so we can close this issue

**Closed by y4izus** 2023-01-17 14:19 UTC
