### ISSUE TITLE
Animated transition between text in the header

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#857] opened 2020-08-24 15:02 UTC
On the overview page and the learn page, we have a highlighted word. That intent of that word is to cycle between other fitting words with some animation. 

For example the learn page says "Start your path towards learning **Qiskit** ". The word Qiskit could cycle between "Quantum Computing", "the basics", "quantum", etc.

**Comment by delapuente** [comment] 2020-09-01 19:11
Duplicate of #804. Closing.

**Closed by delapuente** 2020-09-01 19:11 UTC
Labels: Decoration
