### ISSUE TITLE
Hover animations on buttons

### ISSUE THREAD

**Issue by korgan00** [Qiskit/qiskit.org#902] opened 2020-09-08 12:27 UTC
We can improve some button interactions, for example: links with an arrow. The arrow can be moved slightly to the direction it points.

**Comment by JRussellHuffman** [comment] 2020-09-08 14:47
Super small request: when exploring animations for this, animate in increments of 8px instead of 10px.

**Comment by techtolentino** [comment] 2020-09-08 16:43
@lerongil @korgan00 - should we close this as a duplicate of https://github.com/Qiskit/qiskit.org/issues/609?

**Comment by techtolentino** [comment] 2020-09-08 16:46
Closing this issue as this will be handled in #609 

Thanks!

**Closed by techtolentino** 2020-09-08 16:46 UTC
