### ISSUE TITLE
Error on code cell on The Case for Quantum

### ISSUE THREAD

**Issue by JRussellHuffman** [Qiskit/qiskit.org#2346] opened 2021-12-02 16:27 UTC
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-states/the-case-for-quantum-computers
2. Click on the third code cell (after running the first two)
3. See error

### What is the current behavior?

An error is thrown about a module that isn't found

### What is the expected behavior?

To have the module loaded correctly

### Screenshots (optional but very helpful)

<img width="889" alt="Screen Shot 2021-12-02 at 10 27 31 AM" src="https://user-images.githubusercontent.com/7633881/144462430-e20d78b1-cf4e-4f60-94f8-f3e29872d81a.png">

### Environment (optional but very helpful)
 - all

**Comment by eddybrando** [comment] 2021-12-21 08:47
Also reported in https://github.com/Qiskit/qiskit.org/issues/2325.

**Comment by eddybrando** [comment] 2021-12-21 08:49
Duplicate of https://github.com/Qiskit/qiskit.org/issues/2325.

**Closed by eddybrando** 2021-12-21 08:49 UTC
Labels: bug, project: textbook beta
