### ISSUE TITLE
Bug: Fix header to top of the page

### ISSUE THREAD

**Issue by pandasa123** [Qiskit/qiskit.org#2724] opened 2022-08-01 16:21 UTC
### Steps to reproduce the problem

1. Go to any page
2. Scroll down
3. See the header bar is not fixed to the top of the page

### What is the current behavior?

The top bar is not fixed to the top of the screen

### What is the expected behavior?

When the user scrolls, the header stays fixed to the top of the browser window so that the menu options are still accessible even when the user has scrolled down the page, like platypus

### Screenshots

https://user-images.githubusercontent.com/6241840/182196845-7dd35794-088a-41be-a988-27da7435d2cf.mov

### Additional information

[Related to this issue in platypus](https://github.com/Qiskit/platypus/issues/662)

**Comment by y4izus** [comment] 2023-01-02 12:18
Checking this bug on the current page. I cannot reproduce the bug (I've added two examples for desktop and mobile versions), so I think we can close this issue

https://user-images.githubusercontent.com/17231966/210229798-9ee2e84a-18fe-482f-80a7-e1be2de52a4c.mov


https://user-images.githubusercontent.com/17231966/210230227-7f252865-726f-4bf0-acad-48be61b3a67b.mov

**Closed by y4izus** 2023-01-02 12:18 UTC
Labels: bug, decoration
