### ISSUE TITLE
Wrongly rendered formulas on "Lab 2 Quantum Measurements" learn page

### ISSUE THREAD

**Issue by eddybrando** [Qiskit/qiskit.org#2160] opened 2021-09-15 10:37 UTC
### Steps to reproduce the problem

1. Go to https://learn.qiskit.org/course/ch-labs/lab-2-quantum-measurements.
2. Scroll down to the "**1. Express the expectation values of the Pauli operators [...]**" section.
3. After the second paragraph, take a look at the formula.

### What is the current behavior?

Some formulas on this page are rendered like this:

![Screenshot 2021-09-15 at 12 36 12](https://user-images.githubusercontent.com/22047320/133418506-6b4e2977-d980-4f3e-882d-904ca8b4bea7.png)

### What is the expected behavior?

They should be rendered properly.

**Comment by vabarbosa** [comment] 2021-10-06 13:30
closing as Duplicate of #2184

**Closed by vabarbosa** 2021-10-06 13:30 UTC
Labels: type: bug, education
