### ISSUE TITLE
Bug: Ecosystem search not working for project name

### ISSUE THREAD

**Issue by javabster** [Qiskit/qiskit.org#3398] opened 2023-07-05 14:43 UTC
### Steps to reproduce the problem

1. Go to qiskit.org/ecosystem
2. Click on the extensions tab
3. search for "mthree"
4. See that no project with the name mthree is displayed, even though the project exists with that name

### What is the current behavior?

the search bar on the ecosystem page looks like it is only searching for content in the description, not for the titles of projects

### What is the expected behavior?

users should be able to search the name of a project and have it returned

**Comment by y4izus** [comment] 2023-07-07 10:14
Duplicate of https://github.com/Qiskit/qiskit.org/issues/3397

**Closed by y4izus** 2023-07-07 10:14 UTC
Labels: bug
