### ISSUE TITLE
Factor out common behaviour for LandingCta and AppCta components

### ISSUE THREAD

**Issue by delapuente** [Qiskit/qiskit.org#916] opened 2020-09-15 20:12 UTC
Part of #973 

There is an opportunity for implementing the `LandingCta` component in terms of the `AppCta` component and reuse all the functionality in `AppCta` related to styles and animations.

**Comment by delapuente** [comment] 2020-09-17 18:43
As said in #917, it seems the behaviour is not exactly the same (the spacing between the text and the arrow changes for different sizes) and composition is not as trivial as it seems. Keeping this open and renaming to reflect the opportunity of factoring out some common behaviour.

**Comment by korgan00** [comment] 2020-11-13 17:45
I think we can consider this a duplicate of #973.
In fact, this is older, but #973 has a wider approach. We can move the discussion there.

**Comment by y4izus** [comment] 2021-02-15 14:36
I think this is done [here](https://github.com/Qiskit/qiskit.org/pull/1145). Do you agree @korgan00 @delapuente ?? if yes, I will close it

**Closed** 2021-02-16 11:43 UTC
Labels: code-quality
