### ISSUE TITLE
Improve design for individual pages for each Qiskit Camp

### ISSUE THREAD

**Issue by marinaaisa** [Qiskit/qiskit.org#327] opened 2019-11-25 12:37 UTC
We want to improve the design for Qiskit Camp's individual page so it has a better UX and UI. Example: https://community.qiskit.org/events/asia/

Figma prototype: https://www.figma.com/proto/FT4GSfLDlqMtkjkQLTgrAX/Redesign-Qiskit-Camp-Africa?node-id=122649%3A283&viewport=170%2C138%2C0.13088484108448029&scaling=min-zoom

**Comment by lerongil** [comment] 2019-12-16 05:39
Is this a duplicate of issue #355 @marinaaisa

**Comment by marinaaisa** [comment] 2019-12-16 09:31
I closed the #355 issue. I forgot I already created it haha

**Comment by lerongil** [comment] 2019-12-16 15:45
Thanks did you also see issue #313

**Comment by marinaaisa** [comment] 2019-12-18 14:15
I have a first version of the redesign of Qiskit Camp Africa (it should be the same for every new Qiskit Camp page): https://www.figma.com/proto/FT4GSfLDlqMtkjkQLTgrAX/Redesign-Qiskit-Camp-Africa?node-id=122649%3A283&viewport=170%2C138%2C0.13088484108448029&scaling=min-zoom
@lerongil it´s ready for feedback

**Comment by JRussellHuffman** [comment] 2019-12-18 21:35
I know this feedback might be a little late, but hopefully it is helpful.

In general, the page is really nice! I like the content spacing and how much everything gets to breath. The sections are concise and to the point. There are a couple of structural things that I think could be refined specifically as an event page. 

I think the page (and future event pages) should support two use cases
1- people who are considering going to the event.
2- People are have already committed to going to the event

For (1), we want to market to them properly, which should include
1- what the event is. 
2- why its worth while. Get them excited. This is a premium event and we want people to know it.
3- where/when it is
4- pricing, packages, hotels, and anything else that they want to know before clicking “buy”

For (2), we want to give them all the details they need for the actual event, including
1- agenda
2- calendar
3- logistics
4- first day details (eg. sign in desk location, parking, room numbers, etc)

More or less, the above are present in your layout, but the order it is presented could be refined for future event pages

I also noticed a few things worth keeping in mind
- will this live on the qiskit.org domain? If so, it should have the same top level nav
- I assume the main nav links to sections down the page, which is definitely fitting. The order in the nav should be the same order as down the page.
- the “summer school” thing could technically be different from “what is a qiskit camp?” section.
- I think you could do more under “what is a qiskit camp” to talk about the value of the event, why its worth going, what they will get out of it, etc. Get them excited in that section
- prizes and judging section could use some unpacking. it hasn’t been established that there are contests and it sounds like the whole event might be a contest, which presumably isn’t true.
- the five dropdowns under code of conduct is an interest pattern. What is that interaction? What happens when they select an option?
- An FAQ section would probably be beneficial


I hope all this helps!

**Comment by marinaaisa** [comment] 2019-12-23 17:02
Thank you very much @JRussellHuffman ! I will try to fix the design based on your feedback on the following days. I just saw it, sorry!

At the meanwhile, I´ve adapted this same UI design to the Finland Unconference event:  https://www.figma.com/proto/FT4GSfLDlqMtkjkQLTgrAX/Redesign-Qiskit-Camp-Pages?node-id=122755%3A321&viewport=-228%2C159%2C0.125&scaling=scale-down

**Comment by JRussellHuffman** [comment] 2020-01-10 22:58
I wanted to give some visual design feedback this time around. In general, I think its really nice, and a huge step forward what it looked like before. That said, I have some thoughts to help it be even more refined.

It looks like you are starting to use of the carbon look and feel. If qiskit pages will be using carbon for the time being, I recommend setting up your figma workspace to support carbon components. I can show you how sometime, but it will definitely make life easier so that you won’t have to replicate styles, rewrite CSS, etc. Basically, the carbon team did a lot of heavy lifting so those of us designing/building individual pages don’t have to.

With that in mind, there are a few details it will definitely help with.
Type scale: the type scale could use some refinement and in general, steer away from using bold. Semibold is fine though. The carbon components have a type scale pre-defined, so you could use that. More on the type scale here: https://www.carbondesignsystem.com/guidelines/typography/overview#scale

Grid: the grid is a little inconsistent up and down the page. With carbon, the grid is a 4 column grid and some of the sections are more similar to a 3 column grid. Also, I think content going edge to edge will help, although that may not be specifically noted by carbon. More about the grid here: https://www.carbondesignsystem.com/guidelines/2x-grid/basics

Accessability: The contrast ratio between the purple to white text may be a little hard for lower vision users. Carbon has some guidelines here: https://www.carbondesignsystem.com/guidelines/color/overview#accessibility and what you are showing may be just fine, but its worth double checking.

A lot of the above will fall in place if the carbon components can be imported.
And as usual, this is all food for thought for your consideration. I know qiskit isn’t strictly adopting carbon, but some of these best practices will hopefully improve the overall feel of the page regardless.

**Comment by marinaaisa** [comment] 2020-01-14 11:34
This is great. You can tell me how to import Carbon this afternoon. :) I spoke with Greg Kida some months ago and he told me there wasn't any Figma library for Carbon. So this changes everything and it's very good news! Thank you @JRussellHuffman !

**Comment by delapuente** [comment] 2020-01-27 16:41
I'm going to close this, considering them as a first iteration already reviewed by the event team.

**Closed** 2020-01-27 16:43 UTC
Labels: type: enhancement
