### ISSUE TITLE
navbar states — active, focus, and hover

### ISSUE THREAD

**Issue by techtolentino** [Qiskit/qiskit.org#2270] opened 2021-10-27 17:36 UTC
We need to refactor/consolidate the styles for various states in our application so that our users have a clear understanding of our calls to actions in the Navbar.

- some nav items use a dark-blue, browser-based, rounded outline
- some nav items use a blue rectangle (no border radius)

This story is to improve our implementation/reusing of these styles.

![Screen Shot 2021-10-27 at 10 31 41 AM (2)](https://user-images.githubusercontent.com/6276074/139117134-01045025-bb41-48f9-be99-474ea5c9c215.png)

![Screen Shot 2021-10-27 at 10 31 56 AM (2)](https://user-images.githubusercontent.com/6276074/139117136-d684a76b-836b-411f-96e4-21de507b86ba.png)
![Screen Shot 2021-10-27 at 10 32 01 AM (2)](https://user-images.githubusercontent.com/6276074/139117141-4b194696-5317-4835-a877-ff7e76a66e10.png)

![Screen Shot 2021-10-27 at 10 31 33 AM (2)](https://user-images.githubusercontent.com/6276074/139117132-588295b3-3217-480b-b091-177aaddeaf21.png)

**Comment by y4izus** [comment] 2023-01-03 10:45
I'm not able to reproduce this issue:


https://user-images.githubusercontent.com/17231966/210342185-8f7a3159-fbd0-4940-8856-583de21de19c.mov

I was probably fixed when we created the web-component for the menu. I close the issue

**Closed by y4izus** 2023-01-03 10:45 UTC
Labels: code quality
